site_name: YData-Synthetic
repo_url: https://github.com/ydataai/ydata-synthetic
repo_name: ydataai/ydata-synthetic
edit_uri: ""
dev_addr: 0.0.0.0:1234
site_dir: "static/docs"
nav:
  - Getting started:
    - 'index.md'
    - Overview: 'index.md'
    - Installation: 'getting-started/installation.md'
    - Synthetic Data Generation:
      - "synthetic_data/index.md"
      - UI interface - YData Fabric: "synthetic_data/ydata_fabric_app.md"
      - Generate Single Table:
        - GMM: "synthetic_data/single_table/gmm_example.md"
        - CGAN: "synthetic_data/single_table/cgan_example.md"
        - WGAN: "synthetic_data/single_table/wgan_example.md"
        - WGAN-GP: "synthetic_data/single_table/wgangp_example.md"
        - CTGAN: "synthetic_data/single_table/ctgan_example.md"
        - DRAGAN: "synthetic_data/single_table/dragan_example.md"
        - Cramer GAN: "synthetic_data/single_table/cramer_gan_example.md"
        - CWGAN-GP: "synthetic_data/single_table/cwgangp_example.md"
      - Generate Time-Series:
        - TimeGAN: "synthetic_data/time_series/timegan_example.md"
        - DoppelGANger: "synthetic_data/time_series/doppelganger_example.md"
      - Generate Multiple Tables:
          - Fabric Multi-Table **: "synthetic_data/multi_table/fabric_multitable.md"
      - Frequently Asked Questions: "synthetic_data/faqs.md"
  - Integrations:
      - Great Expectations: "integrations/gx_integration.md"
  - Support: 
    - Help & Troubleshooting: 'support/help-troubleshooting.md'
theme:
  name: material
  language: en
  palette:
    - scheme: ydata
      media: "(prefers-color-scheme: light)"
      primary: custom
  logo: 'https://assets.ydata.ai/oss/ydata-synthetic-_red.png'
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - toc.integrate
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - def_list
  - meta
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - tables
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  version:
    provider: mike
  generator: false
plugins:
  - mkdocstrings